### ISSUE TITLE
residual trading days tests in JDemetra+ 2.x.y

### ISSUE THREAD

**Issue by AQLT** [rjdemetra/rjd3toolkit#7]
In JDemetra+ 2.x.y, the residual trading days tests was perform with an AR(1) model estimated by OLS while in `rjd3toolkit` it is now estimated using another method (ML). In previous versions of `rjd3toolkit` there was a model called `AR` which was also using an ols model :
https://github.com/jdemetra/jdemetra-core/blob/2b12a60f0b7135f00fab7031233ddf93f33045b6/demetra-sa/demetra-sa-r/src/main/java/demetra/sa/r/TradingDaysTests.java#L33-L38
If think it would be usefull to keep this model in order to be able to reproduce the tests used in JDemetra+ 2.x.y

**Comment by palatej** [comment]
Hi Alain, 

I suppressed the test because it was wrong (as the test in JD2). More specifically, the model was:
y(t)= a + b*y(t-1) + c*td(t) + e(t).

A more correct model should be:
y(t) - phi*y(t-1)=a + b*(td(t) - phi*td(t-1)) + e(t)

The new test is based on phi = 1.
In practice, setting phi = 1 doesn't change much the result of the test and it is more robust (and significantly faster).
To be noted that for stationary series, I put phi = 0
